### ISSUE TITLE
Can anyone port beautiful-ui themes from VS Code?

### ISSUE THREAD

**Issue by vadim-96** [microsoft/VS-ColorThemes#70]
I use this theme pack for VS Code: [https://marketplace.visualstudio.com/items?itemName=swashata.beautiful-ui](https://marketplace.visualstudio.com/items?itemName=swashata.beautiful-ui)
It would be great if someone ported these themes, especially the Zenburn theme)

**Comment by jonasnordlund** [comment]
Yes, these are quite a few of the classics there, like those popular base16 themes.

We really need a utility to assist in porting the Visual Studio Code format to Visual Studio. I understand there will not and cannot be a 1:1 conversion match due to differing features but a reasonable automated attempt ought to be possible to at least form a basis where a human can do the fine tuning.
