### ISSUE TITLE
How does one actually use this?

### ISSUE THREAD

**Issue by MJLaukala** [microsoft/VS-ColorThemes#82]
I'm sure it's a great extension but given it's age and not having a single instruction seems a little out of place. All I really need to know is where to find it.

**Comment by phonetagger** [comment]
Wow, I would never have even realized VS-ColorThemes was working if it weren't for @MJLaukala 's issue ticket. I would strongly upvote this issue; I considered just uninstalling it since it looked like it wasn't even working; then I thought I should at least post an issue so someone knows why I uninstalled it, then I saw this issue ticket. @geekcyclist 's response here should be the first thing shown at the top of the [title page](https://github.com/microsoft/VS-ColorThemes), even before the section about "Steps to create a custom theme for this project".

**Comment by justcla** [comment]
Sorry this extension didn't provide any instructions on how to change themes.

The official extension (Color Themes Editor) automatically opens the color themes.

This extension is just a themes pack.

I'm sure I'll never find the time to add a yellow bar at the start of VS (which, I agree is an excellent idea).
But I might be able to update the instructions on the Marketplace website.

**Comment by phonetagger** [comment]
No need to add a yellow bar at the start of VS (I'm not really sure what you mean by that anyway), just the info in MJLaukala's post is quite sufficient, if you just post that at the top of the Github page and maybe also on the Marketplace page.

**Comment by drewnoakes** [comment]
Information added in #84.
